import { Injectable, OnDestroy } from '@angular/core';
import { Subject, BehaviorSubject, fromEvent } from 'rxjs';
import { takeUntil, debounceTime } from 'rxjs/operators';

import { Router } from '@angular/router';
// Menu
export interface Menu {
  headTitle?: string;
  headTitle2?: string;
  path?: string;
  dirchange?: boolean;
  title?: string;
  icon?: string;
  type?: string;
  badgeValue?: string;
  badgeClass?: string;
  active?: boolean;
  selected?: boolean;
  bookmark?: boolean;
  children?: Menu[];
  Menusub?: boolean;
  target?: boolean;
  menutype?: string;
}

@Injectable({
  providedIn: 'root',
})
export class NavService implements OnDestroy {
  private unsubscriber: Subject<any> = new Subject();
  public screenWidth: BehaviorSubject<number> = new BehaviorSubject(
    window.innerWidth
  );

  // Search Box
  public search = false;

  // Language
  public language = false;

  // Mega Menu
  public megaMenu = false;
  public levelMenu = false;
  public megaMenuColapse: boolean = window.innerWidth < 1199 ? true : false;

  // Collapse Sidebar
  public collapseSidebar: boolean = window.innerWidth < 991 ? true : false;

  // For Horizontal Layout Mobile
  public horizontal: boolean = window.innerWidth < 991 ? false : true;

  // Full screen
  public fullScreen = false;
  active: any;

  constructor(private router: Router) {
    this.setScreenWidth(window.innerWidth);
    fromEvent(window, 'resize')
      .pipe(debounceTime(1000), takeUntil(this.unsubscriber))
      .subscribe((evt: any) => {
        this.setScreenWidth(evt.target.innerWidth);
        if (evt.target.innerWidth < 991) {
          this.collapseSidebar = true;
          this.megaMenu = false;
          this.levelMenu = false;
        }
        if (evt.target.innerWidth < 1199) {
          this.megaMenuColapse = true;
        }
      });
    if (window.innerWidth < 991) {
      // Detect Route change sidebar close
      this.router.events.subscribe((event) => {
        this.collapseSidebar = true;
        this.megaMenu = false;
        this.levelMenu = false;
      });
    }
  }

  ngOnDestroy() {
    this.unsubscriber.next;
    this.unsubscriber.complete();
  }

  private setScreenWidth(width: number): void {
    this.screenWidth.next(width);
  }

  MENUITEMS: Menu[] = [
    // Dashboard
    { headTitle: 'MAIN' },
    {
      // title: 'Dashboard',
      // icon: 'bi-house',
      // dirchange: false,
      // type: 'sub',
      // active: false,
      children: [
        // {
        //   title: 'Sales',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/sales',
        // },
        // {
        //   title: 'Analytics',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/analytics',
        // },
        // {
        //   title: 'Ecommerce',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/ecommerce',
        // },
        // {
        //   title: 'Crm',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/crm',
        // },
        // {
        //   title: 'HRM',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/hrm',
        // },
        // {
        //   title: 'NFT',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/nft',
        // },
      
        // {
        //   title: 'Crypto',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/crypto',
        // },
        // {
        //   title: 'Jobs',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/jobs',
        // },
        // {
        //   title: 'Projects',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/projects',
        // },
        // {
        //   title: 'Courses',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/courses',
        // },
        // {
        //   title: 'Stocks',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/stocks',
        // },
        // {
        //   title: 'Personal',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/personal',
        // },
        // {
        //   title: 'Customer',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/dashboard/customer',
        // },
      ],
    },
    {
    title: 'Dashboard',
      icon: 'bi-house',
      dirchange: false,
      active: false,
      type: 'link',
      path: '/dashboard/sales',
    },
    //PAGES
    { headTitle: 'PAGES' },
    {
      title: 'Crm & Sales',
      icon: 'bi-file-earmark',
      type :'link',
      dirchange: false,
      active: false,
      selected: false,
      path: '/dashboard/crm',
      children: [
    //     {
    //       title: 'Blog',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Blog',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/blog/blog',
    //         },
    //         {
    //           title: 'Blog-Details',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/blog/blogdetails',
    //         },
    //         {
    //           title: 'Create-Blog',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/blog/createblog',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Chat',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/chat',
    //     },
    //     {
    //       title: 'Contacts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/contacts',
    //     },
    //     {
    //       title: 'Contactus',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/contactus',
    //     },
    //     {
    //       title: 'Ecommerce',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Add-Products',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/addproducts',
    //         },
    //         {
    //           title: 'Cart',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/cart',
    //         },
    //         {
    //           title: 'Checkout',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/checkout',
    //         },
    //         {
    //           title: 'Edit-Products',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/editproducts',
    //         },
    //         {
    //           title: 'Order-Details',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/order-details',
    //         },
    //         {
    //           title: 'Orders',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/orders',
    //         },

    //         {
    //           title: 'Products',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/products',
    //         },
    //         {
    //           title: 'Product-Details',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/productdetails',
    //         },
    //         {
    //           title: 'Products-List',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/productslist',
    //         },
    //         {
    //           title: 'Wishlist',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/ecommerce/wishlist',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Email',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Mail-App',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/email/mailapp',
    //         },
    //         {
    //           title: 'Mail-Settings',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/email/mailsettings',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Empty',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/empty',
    //     },
    //     {
    //       title: 'Faqs',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/faqs',
    //     },
    //     {
    //       title: 'Filemanager',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Filemanager',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/filemanager/filemanager',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Invoice',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Create-Invoice',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/invoice/createinvoice',
    //         },
    //         {
    //           title: 'Invoice-Details',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/invoice/invoicedetails',
    //         },
    //         {
    //           title: 'Invoice-List',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/pages/invoice/invoicelist',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Landing',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/landing',
    //     },
    //     {
    //       title: 'Jobslanding',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/jobslanding',
    //     },
    //     {
    //       title: 'Notifications',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/notifications',
    //     },
    //     {
    //       title: 'Pricing',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/pricing',
    //     },
    //     {
    //       title: 'Profile',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/profile',
    //     },
    //     {
    //       title: 'Reviews',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/reviews',
    //     },
    //     {
    //       title: 'Team',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/team',
    //     },
    //     {
    //       title: 'Terms-Conditions',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/terms-conditions',
    //     },
    //     {
    //       title: 'Timeline',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/timeline',
    //     },
    //     {
    //       title: 'To-Do-List',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/pages/to-do-list',
    //     },
      ],
    },
    // {
    //   title: 'Adonai',
    //   icon: 'bi-file-earmark',
    //   type :'link',
    //   dirchange: false,
    //   active: false,
    //   selected: false,
    //   path: '/dashboard/adonai',
    // },
    // authentication
    { headTitle: 'AUTHENTICATION' },
    {
      title: 'Accounts & Finace',
      icon: 'bi-key',
      dirchange: false,
      type: 'link',
      active: false,
      selected: false,
      children: [
    //     {
    //       title: 'Coming-Soon',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/authentication/coming-soon',
    //     },
    //     {
    //       title: 'Create-Password',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/create-password/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/create-password/cover',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Lock-Screen',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/lock-screen/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/lock-screen/cover',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Reset-Password',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/reset-password/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/reset-password/cover',
    //         },
    //       ],
    //     },
      
    //     {
    //       title: 'sign-Up',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/sign-up/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/sign-up/cover',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'sign-In',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/sign-in/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/sign-in/cover',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Two-Step-Verification',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Basic',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/two-step-verification/basic',
    //         },
    //         {
    //           title: 'Cover',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/authentication/two-step-verification/cover',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Under-Maintanace',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/authentication/under-maintanace',
    //     },
      ],
    },
    // ERROR
    { headTitle: 'ERROR' },
    {
      title: 'Reports & Controls',
      icon: 'bi- bi-exclamation-triangle',
      dirchange: false,
      type: 'link',
      active: false,
      children: [
        // {
        //   title: 'Error-401',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/error/error401',
        // },
        // {
        //   title: 'Error-404',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/error/error404',
        // },
        // {
        //   title: 'Error-500',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/error/error500',
        // },
      ],
    },
     {
        title: 'Projects',
        dirchange: false,
        type: 'link',
        icon: ' bi-layers side-menu__icon',
        active: false,
        selected: false,
        path: '/dashboard/projects',
      },
      {
        title: 'Project-Details',
        dirchange: false,
        type: 'link',
        icon: ' bi-file-earmark-text side-menu__icon',
        active: false,
        selected: false,
        path: '/dashboard/Project-Details',
      },
      {
        title: 'my-Tasks',
        dirchange: false,
        type: 'link',
        icon: 'bi-layout-text-window side-menu__icon',
        active: false,
        selected: false,
        path: '/dashboard/mytask',
      },
      {
        title: 'Order-Details',
        dirchange: false,
        type: 'link',
        icon: ' bi-file-earmark-text side-menu__icon',
        active: false,
        selected: false,
        path: '/dashboard/Order-Details',
      },
    // APPS
    { headTitle: 'APPS' },
    {
      title: ' 3D Visualizer',
      icon: ' bi-grid side-menu__icon',
      dirchange: false,
      type: 'link',
      active: false,
      children: [
        // {
        //   title: 'Full-calender',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/apps/full-calender',
        // },
        // {
        //   title: 'Gallery',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/apps/gallery',
        // },
        // {
        //   title: 'Sweet-Alerts',
        //   dirchange: false,
        //   type: 'link',
        //   active: false,
        //   selected: false,
        //   path: '/apps/sweet-alerts',
        // },
        // {
        //   title: 'Projects',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Projects-List',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/projects/projects-list',
        //     },
        //     {
        //       title: 'Project-Overview',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/projects/project-overview',
        //     },
        //     {
        //       title: 'Create-Project',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/projects/create-project',
        //     },
        //   ],
        // },
        // {
        //   title: 'Task',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Kanban-Board',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/task/kanban-board',
        //     },
        //     {
        //       title: 'List-View',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/task/list-view',
        //     },
        //     {
        //       title: 'Task-Details',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/task/task-details',
        //     },
        //   ],
        // },
        // {
        //   title: 'Jobs',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Job-Details',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/job-details',
        //     },
        //     {
        //       title: 'Search-Company',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/search-company',
        //     },
        //     {
        //       title: 'Search-Jobs',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/search-jobs',
        //     },
        //     {
        //       title: 'Job-Post',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/job-post',
        //     },
        //     {
        //       title: 'Jobs-List',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/jobs-list',
        //     },
        //     {
        //       title: 'Search-Candidates',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/search-candidates',
        //     },
        //     {
        //       title: 'Candidate-Details',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/jobs/candidate-details',
        //     },
        //   ],
        // },
        // {
        //   title: 'NFT',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Market-Place',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/nft/market-place',
        //     },
        //     {
        //       title: 'NFT-Details',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/nft/nft-details',
        //     },
        //     {
        //       title: 'Create-NFT',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/nft/create-nft',
        //     },
        //     {
        //       title: 'Wallet-Integration',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/nft/wallet-integration',
        //     },
        //     {
        //       title: 'Live-Auction',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/nft/live-auction',
        //     },
        //   ],
        // },
        // {
        //   title: 'CRM',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Companies',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crm/companies',
        //     },
        //     {
        //       title: 'Contacts',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crm/contacts',
        //     },
        //     {
        //       title: 'Deals',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crm/deals',
        //     },
        //     {
        //       title: 'Leads',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crm/leads',
        //     },
        //   ],
        // },
        // {
        //   title: 'Crypto',
        //   dirchange: false,
        //   type: 'sub',
        //   active: false,
        //   selected: false,
        //   children: [
        //     {
        //       title: 'Transactions',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crypto/transactions',
        //     },
        //     {
        //       title: 'Currency-Exchange',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crypto/currency-exchange',
        //     },
        //     {
        //       title: 'Buy-Sell',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crypto/buy-sell',
        //     },
        //     {
        //       title: 'Marketcap',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crypto/marketcap',
        //     },
        //     {
        //       title: 'Wallet',
        //       dirchange: false,
        //       type: 'link',
        //       active: false,
        //       selected: false,
        //       path: '/apps/crypto/wallet',
        //     },
        //   ],
        // },
      ],
    },
    //NESTED-MENU
    // { headTitle: ' NESTED-MENU' },
    // {
    //   title: ' Nested-Menu',
    //   icon: ' bi-layers side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Nested-1',
    //       dirchange: false,
    //       type: 'empty',
    //       active: false,
    //       selected: false,
    //       path: '/nested-menu/nested-1',
    //     },
    //     {
    //       title: 'Nested-2',
    //       dirchange: false,
    //       type: 'sub',
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Nested-2.1',
    //           dirchange: false,
    //           type: 'empty',
    //           active: false,
    //           selected: false,
    //           path: '/nested-menu/nested-2/nested-2-1',
    //         },
    //         {
    //           title: 'Nested-2.2',
    //           dirchange: false,
    //           type: 'empty',
    //           active: false,
    //           selected: false,
    //           path: '/nested-menu/nested-2/nested-2-2',
    //         },
    //       ],
    //     },
    //   ],
    // },
    //UI-ELEMENTS
    // { headTitle: ' UI-ELEMENTS' },
    // {
    //   title: ' UI-Elements',
    //   icon: 'bi-archive side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Alerts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/alerts',
    //     },
    //     {
    //       title: 'Badge',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/badge',
    //     },
    //     {
    //       title: 'Breadcrumb',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/breadcrumb',
    //     },
    //     {
    //       title: 'Buttons',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/buttons',
    //     },
    //     {
    //       title: 'Button-Group',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/button-group',
    //     },
    //     {
    //       title: 'Cards',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/cards',
    //     },
    //     {
    //       title: 'Dropdowns',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/dropdowns',
    //     },
    //     {
    //       title: 'Images-Figures',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/images-figures',
    //     },
    //     {
    //       title: 'List-Group',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/list-group',
    //     },
    //     {
    //       title: 'Navs-Tabs',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/navs-tabs',
    //     },
    //     {
    //       title: 'Object-Fit',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/object-fit',
    //     },
    //     {
    //       title: 'Pagination',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/pagination',
    //     },
    //     {
    //       title: 'Popovers',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/popovers',
    //     },
    //     {
    //       title: 'Progress',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/progress',
    //     },
    //     {
    //       title: 'Spinners',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/spinners',
    //     },
    //     {
    //       title: 'Toasts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/toasts',
    //     },
    //     {
    //       title: 'Tooltips',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/tooltips',
    //     },
    //     {
    //       title: 'Typography',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/ui-elements/typography',
    //     },
    //   ],
    // },
    //UTILITIES
    // { headTitle: 'UTILITIES' },
    // {
    //   title: ' Utilities',
    //   icon: 'bi-award side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Avatars',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/avatars',
    //     },
    //     {
    //       title: 'Borders',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/borders',
    //     },
    //     {
    //       title: 'Breakpoints',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/breakpoints',
    //     },
    //     {
    //       title: 'Colors',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/colors',
    //     },
    //     {
    //       title: 'Columns',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/columns',
    //     },
    //     {
    //       title: 'Flex',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/flex',
    //     },
    //     {
    //       title: 'Gutters',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/gutters',
    //     },
    //     {
    //       title: 'Helpers',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/helpers',
    //     },
    //     {
    //       title: 'Positions',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/positions',
    //     },
    //     {
    //       title: 'Additional-Content',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/utilities/additional-content',
    //     },
    //   ],
    // },
    //FORMS
    // { headTitle: ' FORMS' },
    // {
    //   title: ' Forms',
    //   icon: 'bi-file-earmark-text side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Form-Elements',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Inputs',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/inputs',
    //         },
    //         {
    //           title: 'Checks-Radios',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/checks-radios',
    //         },
    //         {
    //           title: 'Input-Groups',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/input-groups',
    //         },
    //         {
    //           title: 'Form-Select',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/form-select',
    //         },
    //         {
    //           title: 'Range-Sliders',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/range-sliders',
    //         },
    //         {
    //           title: 'Input-Masks',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/input-masks',
    //         },
    //         {
    //           title: 'File-Uploads',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/file-uploads',
    //         },
    //         {
    //           title: 'Date-Time-Picker',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/date-time-picker',
    //         },
    //         {
    //           title: 'Color-Pickers',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-elements/color-pickers',
    //         },
          
           
          
          
        
    //       ],
    //     },
    //     {
    //       title: 'Floating-Labels',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/forms/floating-labels',
    //     },
    //     {
    //       title: 'Form-Layouts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/forms/form-layouts',
    //     },
    //     {
    //       title: 'Form-Editors',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
    //         {
    //           title: 'Quill-Editor',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/forms/form-editors/quill-editor',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Validations',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/forms/validations',
    //     },
    //     {
    //       title: 'Ng-select',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/forms/ng-select',
    //     },
    //   ],
    // },
    //ADVANCED-UI
    // { headTitle: ' ADVANCED-UI' },
    // {
    //   title: 'Advanced-Ui',
    //   icon: 'bi-snow side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Accordions-Collapse',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/accordions-collapse',
    //     },
       
    //     {
    //       title: 'Carousel',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/carousel',
    //     },
    //     {
    //       title: 'Draggable-Cards',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/draggable-cards',
    //     },
    //     {
    //       title: 'Modals-Closes',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/modals-closes',
    //     },
    //     {
    //       title: 'Navbar',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/navbar',
    //     },
    //     {
    //       title: 'Offcanvas',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/offcanvas',
    //     },
    //     {
    //       title: 'Placeholders',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/placeholders',
    //     },
    //     {
    //       title: 'Ratings',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/ratings',
    //     },
    //     {
    //       title: 'Scrollspy',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/scrollspy',
    //     },
    //     {
    //       title: 'Swiper-JS',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/advanced-ui/swiper-js',
    //     },
    //   ],
    // },

    //Widgets
    // { headTitle: 'WIDGETS' },
    // {
    //   title: 'Widgets',
    //   icon: 'bi-gift side-menu__icon"',
    //   active: false,
    //   selected: false,
    //   badgeClass: 'badge badge-sm bg-secondary badge-hide',
    //   badgeValue: 'new',
    //   path: '/widgets',
    //   dirchange: false,
    //   type: 'link',
    // },
    // //TABLES
    // { headTitle: 'TABLES' },
    // {
    //   title: 'Tables',
    //   icon: 'bi-layout-text-window side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   Menusub: true,
    //   active: false,
    //   children: [
    //     {
    //       title: 'Tables',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/tables/tables',
    //     },
    //     {
    //       title: 'ngx-easy-table',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/tables/ngx-easy-table',
    //     },
    //     {
    //       title: 'Ang Material Table',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/tables/ang-material-table',
    //     },
    //   ],
    // },
    //CHARTS
    // { headTitle: 'CHARTS' },
    // {
    //   title: 'Charts',
    //   icon: 'bi-bar-chart side-menu__icon',
    //   dirchange: false,
    //   type: 'sub',
    //   active: false,
    //   children: [
    //     {
    //       title: 'Apex-Charts',
    //       dirchange: false,
    //       type: 'sub',
    //       active: false,
    //       selected: false,
    //       children: [
            // {
            //   title: 'a-Charts',
            //   dirchange: false,
            //   type: 'sub',
            //   active: false,
            //   selected: false,
            //   children: [
                // {
                //   title: 'Area-Charts',
                //   dirchange: false,
                //   type: 'link',
                //   active: false,
                //   selected: false,
                //   path: '/charts/apex-charts/area-charts',
                // },
            //   ]
            // },
    //         {
    //           title: 'Line-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/line-charts',
    //         },
    //         {
    //           title: 'Column-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/column-charts',
    //         },
    //         {
    //           title: 'Bar-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/bar-charts',
    //         },
    //         {
    //           title: 'Mixed-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/mixed-charts',
    //         },
    //         {
    //           title: 'Range-Area-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/range-area-charts',
    //         },
    //         {
    //           title: 'Timeline-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/timeline-charts',
    //         },
    //         {
    //           title: 'Funnel-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/funnel-charts',
    //         },
    //         {
    //           title: 'Candlestick-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/candlestick-charts',
    //         },
    //         {
    //           title: 'Boxplot-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/boxplot-charts',
    //         },
    //         {
    //           title: 'Bubble-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/bubble-charts',
    //         },
    //         {
    //           title: 'Scatter-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/scatter-charts',
    //         },
    //         {
    //           title: 'Heatmap-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/heatmap-charts',
    //         },
    //         {
    //           title: 'Treemap-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/treemap-charts',
    //         },
    //         {
    //           title: 'Pie-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/pie-charts',
    //         },
    //         {
    //           title: 'Radialbar-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/radialbar-charts',
    //         },
    //         {
    //           title: 'Radar-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/radar-charts',
    //         },
    //         {
    //           title: 'Polararea-Charts',
    //           dirchange: false,
    //           type: 'link',
    //           active: false,
    //           selected: false,
    //           path: '/charts/apex-charts/polararea-charts',
    //         },
    //       ],
    //     },
    //     {
    //       title: 'Chartjs-Charts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/charts/chartjs-charts',
    //     },
    //     {
    //       title: 'Echart-Charts',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/charts/echart-charts',
    //     },
    //   ],
    // },
    //MAPS
    // { headTitle: 'MAPS' },
    // {
    //   title: 'MAPS',
    //   icon: 'bi-geo-alt side-menu__icon"',
    //   dirchange: false,
    //   type: 'sub',
    //   Menusub: true,
    //   active: false,
    //   children: [
    //     {
    //       title: 'Google-Map',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/maps/google-map',
    //     },
    //     {
    //       title: 'Leaflet-Map',
    //       dirchange: false,
    //       type: 'link',
    //       active: false,
    //       selected: false,
    //       path: '/maps/leaflet-map',
    //     },
        
    //   ],
    // },
    //icons
    // { headTitle: 'ICONS' },
    // {
    //   title: 'Icons',
    //   icon: ' bi-shop side-menu__icon',
    //   active: false,
    //   selected: false,
    //   badgeClass: 'badge badge-sm bg-secondary badge-hide',
    //   badgeValue: 'new',
    //   path: '/icons',
    //   dirchange: false,
    //   type: 'link',
    // },

    {
            title: 'Pricing',
            dirchange: false,
            icon : 'bi-currency-dollar',
            type: 'link',
            active: false,
            selected: false,
            path: '/pages/pricing',
          },
  ];
  // Array
  items = new BehaviorSubject<Menu[]>(this.MENUITEMS);
}
